services:
  ef_sqlserver:
    container_name: ef-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: yourStrong(!)Password
      MSSQL_PID: Evaluation
    ports:
      - 1433:1433
